/**
 * Spacecraft data loader
 *
 * Loads spacecraft orbital data from spacecraft.json (generated by fetch-spacecraft.ts)
 * and converts to CelestialBody objects for rendering.
 *
 * Supports timeline filtering - spacecraft only appear during their mission dates.
 */

import { type CelestialBody } from '../astronomy/bodies';
import {
  type SpacecraftType,
  type SpacecraftStatus,
  type SpacecraftIconType,
  SPACECRAFT_STATUS_COLORS,
} from '../astronomy/constants';

// JSON data structure (matches fetch-spacecraft.ts output)
interface SpacecraftJsonData {
  generatedAt: string;
  epochJD: number;
  source: string;
  spacecraft: Array<{
    name: string;
    spkid: number;
    missionType: SpacecraftType;
    status: SpacecraftStatus;
    iconType: SpacecraftIconType;
    launchJD: number;
    endJD?: number;
    parentName?: string;
    elements?: {
      a: number;
      e: number;
      i: number;
      L: number;
      longPeri: number;
      longNode: number;
      LDot: number;
    };
    parentCentricElements?: {
      a: number;
      e: number;
      i: number;
      M0: number;
      omega: number;
      Omega: number;
      n: number;
      epoch: number;
    };
  }>;
}

// Storage for loaded data
let spacecraftData: SpacecraftJsonData | null = null;
let allSpacecraftCache: CelestialBody[] | null = null;

/**
 * Convert spacecraft JSON data to CelestialBody object
 */
function spacecraftToCelestialBody(
  craft: SpacecraftJsonData['spacecraft'][0]
): CelestialBody {
  const body: CelestialBody = {
    name: craft.name,
    type: 'probe',
    radius: 0.01,  // ~10m, will render at minimum size
    color: SPACECRAFT_STATUS_COLORS[craft.status],

    // Spacecraft-specific fields
    spkid: craft.spkid,
    missionType: craft.missionType,
    missionStatus: craft.status,
    launchJD: craft.launchJD,
    endJD: craft.endJD,
    iconType: craft.iconType,
  };

  // Add orbital elements
  if (craft.parentCentricElements && craft.parentName) {
    // Planetary orbiter (parent-centric)
    body.parentName = craft.parentName;
    body.parentCentricElements = {
      a: craft.parentCentricElements.a,
      e: craft.parentCentricElements.e,
      i: craft.parentCentricElements.i,
      M0: craft.parentCentricElements.M0,
      omega: craft.parentCentricElements.omega,
      Omega: craft.parentCentricElements.Omega,
      n: craft.parentCentricElements.n,
      epoch: craft.parentCentricElements.epoch,
    };
  } else if (craft.elements) {
    // Heliocentric spacecraft
    body.elements = {
      a: craft.elements.a,
      e: craft.elements.e,
      i: craft.elements.i,
      L: craft.elements.L,
      longPeri: craft.elements.longPeri,
      longNode: craft.elements.longNode,
      LDot: craft.elements.LDot,
    };
  }

  return body;
}

/**
 * Load spacecraft data from JSON file
 * Call this once at startup
 */
export async function loadSpacecraftData(): Promise<void> {
  try {
    // Fetch the JSON file at runtime (works with Vite)
    const response = await fetch('/src/data/spacecraft.json');
    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }
    spacecraftData = await response.json();
    allSpacecraftCache = null; // Reset cache
    console.log(`Loaded ${spacecraftData?.spacecraft.length || 0} spacecraft from spacecraft.json`);
  } catch (err) {
    // Try alternative path for production build
    try {
      const response = await fetch('/data/spacecraft.json');
      if (response.ok) {
        spacecraftData = await response.json();
        allSpacecraftCache = null;
        console.log(`Loaded ${spacecraftData?.spacecraft.length || 0} spacecraft from spacecraft.json`);
        return;
      }
    } catch {
      // Ignore
    }
    console.log('spacecraft.json not found. Run: npx ts-node scripts/fetch-spacecraft.ts');
    spacecraftData = null;
  }
}

/**
 * Get all spacecraft as CelestialBody objects
 */
export function getAllSpacecraft(): CelestialBody[] {
  if (!spacecraftData?.spacecraft) {
    return [];
  }

  // Use cache if available
  if (allSpacecraftCache) {
    return allSpacecraftCache;
  }

  allSpacecraftCache = spacecraftData.spacecraft.map(spacecraftToCelestialBody);
  return allSpacecraftCache;
}

/**
 * Get spacecraft visible at a given Julian date (timeline filtering)
 * Only returns spacecraft that have launched but haven't ended
 */
export function getVisibleSpacecraft(julianDate: number): CelestialBody[] {
  if (!spacecraftData?.spacecraft) {
    return [];
  }

  return spacecraftData.spacecraft
    .filter(craft => {
      // Must have launched
      if (julianDate < craft.launchJD) return false;

      // If ended, must be before end date
      if (craft.endJD && julianDate > craft.endJD) return false;

      return true;
    })
    .map(spacecraftToCelestialBody);
}

/**
 * Get spacecraft by mission type
 */
export function getSpacecraftByType(missionType: SpacecraftType): CelestialBody[] {
  if (!spacecraftData?.spacecraft) {
    return [];
  }

  return spacecraftData.spacecraft
    .filter(craft => craft.missionType === missionType)
    .map(spacecraftToCelestialBody);
}

/**
 * Get spacecraft by status
 */
export function getSpacecraftByStatus(status: SpacecraftStatus): CelestialBody[] {
  if (!spacecraftData?.spacecraft) {
    return [];
  }

  return spacecraftData.spacecraft
    .filter(craft => craft.status === status)
    .map(spacecraftToCelestialBody);
}

/**
 * Check if spacecraft data is loaded
 */
export function hasSpacecraftData(): boolean {
  return spacecraftData !== null && spacecraftData.spacecraft.length > 0;
}

/**
 * Get spacecraft data metadata
 */
export function getSpacecraftMetadata(): { generatedAt: string; epochJD: number; count: number } | null {
  if (!spacecraftData) return null;

  return {
    generatedAt: spacecraftData.generatedAt,
    epochJD: spacecraftData.epochJD,
    count: spacecraftData.spacecraft.length,
  };
}
